version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
  grafana-tempo:
    image: grafana/tempo:main-06487cc
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250"  # Jaeger - GRPC
      - "55680"  # OpenTelemetry
      - "4317" # grpc
      - "4318" # http
      - "3200:3200"   # tempo
  grafana:
    image: grafana/grafana:11.4.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '3000:3000'
    volumes:
      - ./config/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - tempo-query

  tempo-query:
    image: grafana/tempo-query:main-82de08f-arm64
    command: [ "-config=/etc/tempo-query.yaml" ]
    volumes:
      - ./config/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    depends_on:
      - grafana-tempo


  otel-collector:
    image: otel/opentelemetry-collector:0.115.1
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - '4318:4318' # 开启http
    depends_on:
      - grafana-tempo
#      - analyzer-server
#
#  analyzer-server:
#    image: carlson-zyc/otel-receiver-server:v1.0.0
  pg-db:
    image: postgres:14.17
    ports:
      - "5432:5432"
    volumes:
      - /Users/zyc/db_volume/pg/oteldemo/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tracing