tempo:
  host: http://127.0.0.1:3200 # 必须使用http开头
server:
  port: 8050
datasource:
#  host: postgresql://postgres:secret@localhost:5432/tracing?sslmode=disable
  host: postgresql://postgres:Z1p5qq30!e@101.37.229.179:5800/flare?sslmode=disable

httpclient:
  tempo:
    dev:
      host: http://127.0.0.1:3200 # 必须使用http开头
  flare-admin:
    dev:
      host: http://127.0.0.1:8800