drop schema if exists oteldemo cascade;
create schema oteldemo;
alter schema oteldemo owner to postgres;

drop table if exists oteldemo.pattern;
create table oteldemo.pattern
(
    id         integer generated by default as identity,
    name       varchar      default ''    not null,
    "desc"     varchar(512) default ''    not null,
    graph_data jsonb                      not null,
    create_at  timestamp    default now() not null
);
comment on table oteldemo.pattern is '需要检验的pattern';
comment on column oteldemo.pattern.name is '名字';

