// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 需要检验的pattern
type OteldemoPattern struct {
	ID pgtype.Int4
	// 名字
	Name      string
	Desc      string
	GraphData []byte
	CreateAt  pgtype.Timestamp
}
