apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    role: busybox
    app: reversesh-server
spec:
  containers:
    - name: busybox
      image: myregistry.com/library/busybox:v2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4444
          protocol: TCP
      command: ["sh", "-c", "tail -f /dev/null"]
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
spec:
  selector:
    app: reversesh-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4444
  type: ClusterIP

