apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-3
data:
  application.yaml: |
    serviceName: svc3
    otelEndPoint: "otel-collector:4318"
    port: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc3
  labels:
    app: svc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc3
  template:
    metadata:
      name: svc3
      labels:
        app: svc3
    spec:
      containers:
        - name: svc3
          image: registry.cn-shanghai.aliyuncs.com/carl-zyc/svc:svc3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
              protocol: TCP
          volumeMounts:
            - mountPath: /app/application.yaml
              name: application-config-volume
              subPath: application.yaml
      restartPolicy: Always
      volumes:
        - name: application-config-volume
          configMap:
            name: application-config-3
---
apiVersion: v1
kind: Service
metadata:
  name: svc3
spec:
  selector:
    app: svc3
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
