apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-4
data:
  application.yaml: |
    serviceName: svc4
    otelEndPoint: "otel-collector:4318"
    port: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc4
  labels:
    app: svc4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc4
  template:
    metadata:
      name: svc4
      labels:
        app: svc4
    spec:
      containers:
        - name: svc4
          image: registry.cn-shanghai.aliyuncs.com/carl-zyc/svc:svc4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
              protocol: TCP
          volumeMounts:
            - mountPath: /app/application.yaml
              name: application-config-volume
              subPath: application.yaml
      restartPolicy: Always
      volumes:
        - name: application-config-volume
          configMap:
            name: application-config-4
---
apiVersion: v1
kind: Service
metadata:
  name: svc4
spec:
  selector:
    app: svc4
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
