apiVersion: "v1"
kind: "Service"
metadata:
  name: "zero-trust"
  namespace: "immune-security"
spec:
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8000
  selector:
    app: "zero-trust"
  type: "ClusterIP"